---
title: "For-loop_exercises_with_dplyr_problem"
author: "John DeFilippo"
date: "October 21, 2015"
output: html_document
---

```{r}
# 1) Print each value of this matrix.

mat <- matrix(1:100, nrow = 10, ncol = 10)
for (i in 1:length (mat)) {
  print(i)
}
```

```{r}
# 2) Multiply each value in this matrix by 7 and store it in a 10 x 10 matrix

mat <- matrix(1:100, nrow = 10, ncol = 10)
nat <- matrix(NA, nrow = 10, ncol = 10)
for (i in 1:length(mat)){
  nat[i] <- mat[i]*7
}
nat
```

```{r}
# 3a) Print these values as part of a string that looks something like 'n = 16'.

#Try to describe in words how I creating the vector of numbers that you are going to use.

set.seed(1)
x <- round(runif(min = 10, max = 100, n = 15))
for (i in 1:length(x)){
  print(paste('n =', x[i]))
}
```

```{r}
# 3b) Now modify this loop to store these strings in a new vector called counts.

set.seed(1)
x <- round(runif(min = 10, max = 100, n = 15))
for (i in 1:length(x)){
  counts <- (paste('n =', x[i]))
  print(counts)
}
```

```{r}
# 4) Make a vector for which each entry is 2 raised to the power of it’s index (ex: the 3rd item in the vector is equal to 2^3).
#For example your loop should return a vector that looks something like this:
#  2, 4, 8, 16, 64, …, 1024

for (i in 1:10) {
  two_power <- 2 ^ i
  print(two_power)
}
```

```{r}
# 5) Make a matrix where each entry, using indexes i for row and j for column, is equivalent to i*j. Your final output should look like:

m <- matrix(NA, 12, 12)
for (n in 1:length(m)) {
  i <- slice.index(m,1)
  j <- slice.index(m,2)
  m[n] <- i[n]*j[n]
}
m
```

```{r}
# 6) Make a vector where each entry is TRUE or FALSE, based on whether it’s index is even or odd.

x <- 1:10
y <- vector()
y <- x %% 2 == 0
y
```

```{r}
# 7) Run this code to set yourself up for question 7.

taxa <- c('Coral', 'fish', 'Fish', 'Phytoplankton', 'coral', 'phytoplankton', 
          'zooplankton', 'Zooplankton', 'Echinoderms', 'echinoderms', 
          'Cephalopods', 'cephalopods')

taxa_values <- sample(taxa, size = 100, replace=TRUE)
set.seed(1)
counts <- round(runif(min = 10, max = 500, n = 100))

taxa_counts <- data.frame(taxa = taxa_values, abundance = counts)

# Convert duplicate upper and lower case to all upper
taxa_caps <- toupper(taxa_values)
taxacap_counts <- data.frame(taxa = taxa_caps, abundance = counts)
```

```{r}
# 7a) Using dplyr, calculate the mean abundance of each taxonomic group, what do you notice about the output? Is it what you would expect?

aggregate(taxacap_counts['abundance'], by = taxacap_counts['taxa'], mean)

# OK, figured out dplyr way

group_by(taxacap_counts, taxa) %>%
  summarize(mean = mean(abundance))

```

```{r}
# 7b) Hopefully not. What’s going on? Can you fix it?

# I dunno, was it the upper/lower case duplicates?
```





