data(mtcars)
mtcars$mpg
mean(mtcars$mpg)
str(mtcars)
getwd()
statesInfo <- read.csv('stateData.csv')
setwd('./EDA_Course_Materials/lesson2/')
subset(statesInfo, state.region == 1)
statesInfo[statesInfo$state.region == 1, ]
str(statesInfo)
reddit <- read.csv('reddit.csv')
str(reddit)
levels(reddit$age.range)
library(ggplot2)
qplot(data = reddit, x= age.range)
?factor()
is.ordered(reddit)
